---
- platform: template
  switches:
    sky_q_living_room:
      value_template: >
        "{{ is_state('binary_sensor.sky_q_living_room_power_status', 'on') }}"
      turn_on:
        service: script.sky_q_living_room_power
      turn_off:
        service: script.sky_q_living_room_power
