---
- platform: mqtt
  name: DustSensor
  state_topic: "home/airquality/dust"
  unit_of_measurement: 'pcs/0.01cf'
- platform: mqtt
  name: RsSensor
  state_topic: "home/airquality/rs"
- platform: mqtt
  name: hchoSensor
  state_topic: "home/airquality/hcho"
  unit_of_measurement: 'ppm'
- platform: mqtt
  name: nh3Sensor
  state_topic: "home/airquality/nh3"
  unit_of_measurement: 'ppm'
- platform: mqtt
  name: coSensor
  state_topic: "home/airquality/co"
  unit_of_measurement: 'ppm'
- platform: mqtt
  name: no2Sensor
  state_topic: "home/airquality/no2"
  unit_of_measurement: 'ppm'
- platform: mqtt
  name: c4h10Sensor
  state_topic: "home/airquality/c4h10"
  unit_of_measurement: 'ppm'
- platform: mqtt
  name: ch4Sensor
  state_topic: "home/airquality/ch4"
  unit_of_measurement: 'ppm'
- platform: mqtt
  name: h2Sensor
  state_topic: "home/airquality/h2"
  unit_of_measurement: 'ppm'
- platform: mqtt
  name: c2h6ohSensor
  state_topic: "home/airquality/c2h5oh"
  unit_of_measurement: 'ppm'
- platform: mqtt
  name: humSensor
  state_topic: "home/airquality/hum"
  unit_of_measurement: '%'
- platform: mqtt
  name: HATempSensor
  state_topic: "home/airquality/HATemp"
  unit_of_measurement: '°C'
- platform: mqtt
  name: HAPresSensor
  state_topic: "home/airquality/HAPres"
  unit_of_measurement: 'bar'
