---
# https://home-assistant.io/components/sensor.template/
- platform: template
  sensors:
    robwifi:
      value_template: '{% if is_state("device_tracker.robs_iphone", "home") %}
      Online{% else %}Offline{% endif %}'

    kirstywifi:
      value_template: >
        '{% if is_state("device_tracker.kirstys_iphone", "home")
        %}Online{% else %}Offline{% endif %}'

    since_last_boot_templated:
      value_template: >-
        {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
        {%- set count = slb | length -%}
        {%- set hms = slb[count - 1] -%}
        {%- set hms_trimmed = hms.split('.')[0] -%}
        {%- set hms_split = hms_trimmed.split(':') -%}
        {%- set hours = hms_split[0] | int -%}

        {%- if count == 3 -%}
          {{ slb[0] ~ ' ' ~ slb[1] ~ ' ' }}
        {%- endif -%}
        {%- if hours > 0 -%}
          {%- if hours == 1 -%}
            1 hour
          {%- else -%}
            {{ hours }} hours
          {%- endif -%}
        {%- endif -%}
