name: TestHomeAssistantConfig

on:
  push:
    branches:
      - master

jobs:
  test_with_home_assistant:
    name: Test with Home Assistant (Python, HA)
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: [3.6, 3.7, 3.8]
        ha-version: ["stable","beta"]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools aiohttp_cors wheel colorlog==4.0.2
        sudo apt-get update -qq
        sudo apt-get install -y libudev-dev python-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev
        for file in $(find custom_components/ -name "manifest.json"); do
          cat "$file" | for req in $(jq .requirements[]);
            do pip3 install $(echo "$req" | jq -r .);
            done;
          done

    - name: Install Home Assistant ${{ matrix.ha-version }}
      run: |
        if [ ${{ matrix.ha-version }} == "stable" ]; then
          python3 -m venv homeassistant
          cd homeassistant
          source bin/activate
          python3 -m pip install homeassistant
        elif [ ${{ matrix.ha-version }} == "beta" ]; then
          python3 -m venv homeassistant
          cd homeassistant
          source bin/activate
          python3 -m pip install --pre homeassistant
        fi

    - name: Prep HA Config Files to work with CI
      run: |
          mv test_secrets.yaml secrets.yaml
          mv imageprocessing/image_processing.yaml imageprocessing/image_processing.ignore
          mv sensors/rest.yaml sensors/rest.ignore
          touch ./home-assistant_v2.db
          touch ./home-assistant.log

    - name: Home Assistant configuration check
      run: |
        echo "Testing with this configuration:"
        cat configuration.yaml
        echo ""
        homeassistant/bin/hass --script check_config --config .
